# Generated by Django 5.0.7 on 2024-07-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакти', 'verbose_name_plural': 'Контакти'},
        ),
    ]
