# Generated by Django 5.0.7 on 2024-07-31 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options'),
        ('listings', '0005_listing_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Контакти'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='listing_id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='listings.listing'),
        ),
    ]
