# Generated by Django 5.0.7 on 2024-08-27 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0005_listing_state'),
        ('realtors', '0002_alter_realtor_options_alter_realtor_hire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='first_name', max_length=200)),
                ('message', models.TextField(blank=True, db_column='feedback_message')),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('listing', models.ForeignKey(db_column='feedback_property_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='listings.listing')),
                ('realtor', models.ForeignKey(db_column='feedback_realtor_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='realtors.realtor')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
