# Generated by Django 5.0.7 on 2024-08-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, db_column='first_name', max_length=200, null=True),
        ),
    ]
