# Generated by Django 5.0.7 on 2024-07-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_options_alter_photos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={},
        ),
    ]
