# Generated by Django 5.0.7 on 2024-07-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_options_alter_photos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Обяви', 'verbose_name_plural': 'Обяви'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Снимки', 'verbose_name_plural': 'Снимки'},
        ),
    ]
