# Generated by Django 5.0.7 on 2024-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_options_alter_photos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
