# Generated by Django 5.0.7 on 2024-09-05 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GARAGE', 'Garage'), ('POOL', 'Pool'), ('PARKING', 'Parking'), ('GARDEN', 'Garden')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Обява', 'verbose_name_plural': 'Обяви'},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='pool',
        ),
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('BGN', 'Bulgarian Lev')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='floors',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='floors_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('MEZONET', 'Mezonet'), ('GARAGE', 'Garage'), ('MULTYROOMS', 'Multyrooms'), ('2-ROOMS', '2 Rooms')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='type_building',
            field=models.CharField(choices=[('STONES', 'Stones'), ('METAL', 'Metal')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='year_of_construction',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='more',
            field=models.ManyToManyField(blank=True, to='listings.option'),
        ),
    ]
