# Generated by Django 5.0.7 on 2024-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_option_alter_listing_options_remove_listing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(choices=[('Гараж', 'Garage'), ('Басейн', 'Pool'), ('Паркинг', 'Parking'), ('Градина', 'Garden')], max_length=20, unique=True),
        ),
    ]
