# Generated by Django 5.0.7 on 2024-09-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_option_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='toilet',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
