# Generated by Django 5.0.7 on 2024-09-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('BGN', 'Лев')], max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('1-стаен', '1-стаен'), ('2-стаен', '2-стаен'), ('3-стаен', '3-стаен'), ('4-стаен', '4-стаен'), ('Многостаен', 'Многостаен'), ('Офис', 'Офис'), ('Студио', 'Студио'), ('Ателие', 'Ателие'), ('Мезонет', 'Мезонет'), ('Къща', 'Къща'), ('Етаж от къща', 'Етаж от къща'), ('Хотел', 'Хотел'), ('Парцел', 'Парцел'), ('Заведение', 'Заведение'), ('Гараж', 'Гараж'), ('Земеделска земя', 'Земеделска земя')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type_building',
            field=models.CharField(choices=[('Панел', 'Панел'), ('Тухла', 'Тухла'), ('Гредоред', 'Гредоред'), ('ЕПК', 'ЕПК'), ('Сглобяема конструкция', 'Сглобяема конструкция')], max_length=30),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(choices=[('Гараж', 'Гараж'), ('Басейн', 'Басейн'), ('Паркинг', 'Паркинг'), ('Градина', 'Градина'), ('В строеж', 'В строеж'), ('С преход', 'С преход'), ('Асансьор', 'Асансьор')], max_length=20, unique=True),
        ),
    ]
