# Generated by Django 5.0.7 on 2024-09-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listing_currency_alter_listing_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more_options', to='listings.listing')),
            ],
            options={
                'verbose_name': 'More_options',
                'verbose_name_plural': 'more_options',
            },
        ),
    ]
