# Generated by Django 5.0.7 on 2024-09-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_moreoptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moreoptions',
            options={'verbose_name': 'Допълнителни опции', 'verbose_name_plural': 'Допълнителни опции'},
        ),
        migrations.AlterField(
            model_name='moreoptions',
            name='name',
            field=models.CharField(choices=[('Гараж', 'Гараж'), ('Басейн', 'Басейн'), ('Паркинг', 'Паркинг'), ('Градина', 'Градина'), ('В строеж', 'В строеж'), ('С преход', 'С преход'), ('Асансьор', 'Асансьор')], max_length=20, unique=True),
        ),
    ]
