# Generated by Django 5.0.7 on 2024-09-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_listing_description_alter_listing_floors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='more',
        ),
    ]
