# Generated by Django 5.0.7 on 2024-09-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_remove_listing_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='year_of_construction',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
