# Generated by Django 5.0.7 on 2024-09-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_listing_year_of_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='year_of_construction',
            field=models.DateTimeField(),
        ),
    ]
