# Generated by Django 5.0.7 on 2024-09-05 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_listing_year_of_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='year_of_construction',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
