# Generated by Django 5.0.7 on 2024-09-05 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_listing_year_of_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='year_of_construction',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
