# Generated by Django 5.0.7 on 2024-09-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_alter_moreoptions_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
