# Generated by Django 5.0.7 on 2024-09-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_option_listing_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditionaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AlterField(
            model_name='listing',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, to='listings.aditionainfo'),
        ),
    ]
