# Generated by Django 5.0.7 on 2024-09-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_aditionainfo_delete_option_alter_listing_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='option',
            new_name='aditional_option',
        ),
    ]
