# Generated by Django 5.0.7 on 2024-09-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_rename_option_listing_aditional_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='aditional_option',
        ),
        migrations.AddField(
            model_name='listing',
            name='aditional_info',
            field=models.ManyToManyField(blank=True, null=True, to='listings.aditionainfo'),
        ),
    ]
