# Generated by Django 5.0.7 on 2024-09-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_remove_listing_aditional_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='aditional_info',
            field=models.ManyToManyField(blank=True, to='listings.aditionainfo'),
        ),
    ]
