# Generated by Django 5.0.7 on 2024-09-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_listing_aditional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='aditional_info',
        ),
        migrations.DeleteModel(
            name='AditionaInfo',
        ),
    ]
