# Generated by Django 5.0.7 on 2024-09-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_rename_type_listing_type_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreoptions',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
