# Generated by Django 5.0.7 on 2024-09-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_moreoptions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='side_view',
            field=models.CharField(choices=[('Западно изложение', 'Западно изложение'), ('Южно изложение', 'Южно изложение'), ('Северно изложение', 'Северно изложение'), ('Североизточното изложение', 'Североизточното изложение'), ('Северозападното изложение', 'Северозападното изложение'), ('Югозапад изложение', 'Югозапад изложение')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
