# Generated by Django 5.0.7 on 2024-09-15 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_listing_side_view'),
        ('realtors', '0002_alter_realtor_options_alter_realtor_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor'),
        ),
    ]
