# Generated by Django 5.0.7 on 2024-09-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_alter_listing_realtor'),
        ('realtors', '0002_alter_realtor_options_alter_realtor_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='realtors.realtor'),
        ),
    ]
