# Generated by Django 5.0.7 on 2024-09-15 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_alter_listing_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='listings.listing'),
        ),
    ]
