# Generated by Django 5.0.7 on 2024-09-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_listing_extra_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='more_options',
        ),
        migrations.DeleteModel(
            name='MoreOptions',
        ),
    ]
