# Generated by Django 5.0.7 on 2024-09-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_alter_listing_side_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
