# Generated by Django 5.0.7 on 2024-09-26 13:18

import datetime
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_alter_listing_extra_options_alter_listing_title'),
        ('realtors', '0002_alter_realtor_options_alter_realtor_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('BGN', 'Лев')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='extra_options',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Гараж', 'Гараж'), ('Басейн', 'Басейн'), ('Паркинг', 'Паркинг'), ('Градина', 'Градина'), ('В строеж', 'В строеж'), ('С преход', 'С преход'), ('Асансьор', 'Асансьор'), ('Луксозен имот', 'Луксозен имот'), ('Саниран', 'Саниран'), ('Ток', 'Ток'), ('Вода', 'Вода'), ('Канализация', 'Канализация'), ('Виза', 'Виза'), ('В регулация', 'В регулация'), ('Преходен', 'Преходен'), ('Тежести', 'Тежести'), ('Таван', 'Таван'), ('Склад в апартамента', 'Склад в апартамента'), ('Технически паспорт на сградата', 'Технически паспорт на сградата'), ('Мазе', 'Мазе'), ('Идеални части от земята', 'Идеални части от земята'), ('Ключ', 'Ключ'), ('Капариран имот', 'Капариран имот'), ('Позволява домашен любимец', 'Позволява домашен любимец'), ('Намалена цена', 'Намалена цена'), ('За инвестиции', 'За инвестиции')], max_length=292, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='realtors.realtor'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='toilet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type_building',
            field=models.CharField(blank=True, choices=[('Панел', 'Панел'), ('Тухла', 'Тухла'), ('Гредоред', 'Гредоред'), ('ЕПК', 'ЕПК'), ('Сглобяема конструкция', 'Сглобяема конструкция')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type_choice',
            field=models.CharField(blank=True, choices=[('1-стаен', '1-стаен'), ('2-стаен', '2-стаен'), ('3-стаен', '3-стаен'), ('4-стаен', '4-стаен'), ('Многостаен', 'Многостаен'), ('Офис', 'Офис'), ('Студио', 'Студио'), ('Ателие', 'Ателие'), ('Мезонет', 'Мезонет'), ('Къща', 'Къща'), ('Етаж от къща', 'Етаж от къща'), ('Хотел', 'Хотел'), ('Парцел', 'Парцел'), ('Заведение', 'Заведение'), ('Гараж', 'Гараж'), ('Земеделска земя', 'Земеделска земя')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_of_construction',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
