# Generated by Django 5.0.7 on 2024-10-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_alter_listing_bathrooms_alter_listing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
