# Generated by Django 5.0.7 on 2024-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_alter_listing_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='estate_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
