# Generated by Django 5.0.7 on 2024-10-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_listing_estate_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_main',
        ),
    ]
