# Generated by Django 5.0.7 on 2025-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_remove_listing_photo_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('BGN', 'Лев')], db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='estate_code',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type_building',
            field=models.CharField(blank=True, choices=[('Панел', 'Панел'), ('Тухла', 'Тухла'), ('Гредоред', 'Гредоред'), ('ЕПК', 'ЕПК'), ('Сглобяема конструкция', 'Сглобяема конструкция')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type_choice',
            field=models.CharField(blank=True, choices=[('1-стаен', '1-стаен'), ('2-стаен', '2-стаен'), ('3-стаен', '3-стаен'), ('4-стаен', '4-стаен'), ('Многостаен', 'Многостаен'), ('Офис', 'Офис'), ('Студио', 'Студио'), ('Ателие', 'Ателие'), ('Мезонет', 'Мезонет'), ('Къща', 'Къща'), ('Етаж от къща', 'Етаж от къща'), ('Хотел', 'Хотел'), ('Парцел', 'Парцел'), ('Заведение', 'Заведение'), ('Гараж', 'Гараж'), ('Земеделска земя', 'Земеделска земя')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
