# Generated by Django 5.0.7 on 2024-08-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='first_name', max_length=200)),
                ('phone', models.CharField(db_column='phone', max_length=10)),
                ('message', models.TextField(blank=True, db_column='feedback_message')),
                ('inquiry_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiry',
            },
        ),
    ]
