# Generated by Django 5.0.7 on 2024-10-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_message', '0002_inquiry_type_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='type_property',
            field=models.CharField(choices=[('1-bed', '1-стаен'), ('2-bed', '2-стаен'), ('3-bed', '3-стаен'), ('4-bed', '4-стаен'), ('multi-bed', 'Многостаен'), ('office', 'Офис'), ('studio', 'Студио'), ('atelier', 'Ателие'), ('maisonette', 'Мезонет'), ('house', 'Къща'), ('floor-house', 'Етаж от къща'), ('hotel', 'Хотел'), ('parcel', 'Парцел'), ('restaurant', 'Заведение'), ('garage', 'Гараж'), ('agricultural-land', 'Земеделска земя')], db_column='type_property', default='Вид имот', max_length=20),
        ),
    ]
