# Generated by Django 5.0.7 on 2024-10-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_message', '0003_alter_inquiry_type_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inquiries/images/')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inquiry_message.inquiry')),
            ],
            options={
                'verbose_name_plural': 'Inquiry Images',
            },
        ),
    ]
