# Generated by Django 5.0.7 on 2024-10-06 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_message', '0006_inquiry_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(blank=True, db_column='feedback_message', null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='type_property',
            field=models.CharField(blank=True, choices=[('1-bed', '1-стаен'), ('2-bed', '2-стаен'), ('3-bed', '3-стаен'), ('4-bed', '4-стаен'), ('multi-bed', 'Многостаен'), ('office', 'Офис'), ('studio', 'Студио'), ('atelier', 'Ателие'), ('maisonette', 'Мезонет'), ('house', 'Къща'), ('floor-house', 'Етаж от къща'), ('hotel', 'Хотел'), ('parcel', 'Парцел'), ('restaurant', 'Заведение'), ('garage', 'Гараж'), ('agricultural-land', 'Земеделска земя')], db_column='type_property', default='Вид имот', max_length=20, null=True),
        ),
    ]
