# Generated by Django 5.0.7 on 2024-10-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_message', '0007_alter_inquiry_message_alter_inquiry_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, db_column='phone', max_length=10, null=True),
        ),
    ]
