# Generated by Django 5.0.7 on 2024-10-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_message', '0008_alter_inquiry_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='phone_number',
        ),
    ]
